# Generated by Django 3.2.5 on 2021-07-25 09:47

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=1, max_length=200, verbose_name='Objektname')),
                ('description', models.TextField(max_length=2048, verbose_name='Beschreibung')),
                ('photo', models.ImageField(blank=True, default=0, upload_to='', verbose_name='Bild')),
            ],
            options={
                'verbose_name': 'Gebäude',
                'verbose_name_plural': 'Gebäude',
            },
        ),
        migrations.CreateModel(
            name='ExtraCosts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typ', models.CharField(choices=[('Heizung', 'Heizung'), ('Wasser', 'Wasser'), ('Allg. NK', 'Allg. NK')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('a_conto', models.CharField(choices=[('a', 'à conto'), ('p', 'pauschal')], default='a', max_length=10)),
            ],
            options={
                'verbose_name': 'Nebenkosten',
                'verbose_name_plural': 'Nebenkosten',
            },
        ),
        migrations.CreateModel(
            name='Rent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200, verbose_name='Beschreibung')),
                ('rent', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Mietpreis (SFR)')),
                ('start_date', models.DateField(default=datetime.datetime(2021, 7, 25, 9, 47, 21, 931583, tzinfo=utc))),
                ('end_date', models.DateField(default=datetime.datetime(2021, 7, 25, 9, 47, 21, 931583, tzinfo=utc))),
                ('aktiv', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Mietzins',
                'verbose_name_plural': 'Mietzins',
            },
        ),
        migrations.CreateModel(
            name='Renter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(blank=True, max_length=200, verbose_name='Firma')),
                ('first_name', models.CharField(max_length=200, verbose_name='Vorname')),
                ('last_name', models.CharField(max_length=200, verbose_name='Nachname')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('phone_number', models.CharField(max_length=200, verbose_name='Telefonnummer')),
                ('conto_number', models.CharField(default=0, max_length=200, verbose_name='IBAN Nummer')),
                ('address', models.CharField(default=0, max_length=200, verbose_name='Strasse')),
                ('address_Nr', models.IntegerField(default=0, verbose_name='Strassennummer')),
                ('city', models.CharField(default=0, max_length=200, verbose_name='Wohnort')),
                ('city_code', models.IntegerField(default=0, verbose_name='PLZ')),
                ('first_name_2nd', models.CharField(blank=True, max_length=200, verbose_name='Zweitmieter Vorname')),
                ('last_name_2nd', models.CharField(blank=True, max_length=200, verbose_name='Zweitmieter Nachname')),
                ('activ', models.BooleanField(default=False, verbose_name='aktiv')),
            ],
            options={
                'verbose_name': 'Mieter',
                'verbose_name_plural': 'Mieter',
            },
        ),
        migrations.CreateModel(
            name='RentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(default=datetime.datetime(2021, 7, 25, 9, 47, 21, 932583, tzinfo=utc))),
                ('end_date', models.DateField(default=datetime.datetime(2021, 7, 25, 9, 47, 21, 932583, tzinfo=utc))),
                ('activ', models.BooleanField(default=False, verbose_name='aktiv')),
                ('miete', models.ManyToManyField(to='verwaltung.Rent')),
                ('mieter', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='verwaltung.renter')),
                ('nebenkosten', models.ManyToManyField(to='verwaltung.ExtraCosts')),
            ],
            options={
                'verbose_name': 'Mietzinsprofil',
                'verbose_name_plural': 'Mietzinsprofil',
            },
        ),
        migrations.CreateModel(
            name='Year',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typ', models.IntegerField(default=2010)),
            ],
            options={
                'verbose_name': 'Jahr',
                'verbose_name_plural': 'Jahr',
            },
        ),
        migrations.CreateModel(
            name='RentReceipts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum', models.DateField(default=datetime.datetime(2021, 7, 25, 9, 47, 21, 937580, tzinfo=utc))),
                ('month', models.CharField(choices=[('JA', 'Januar'), ('FE', 'Februar'), ('MA', 'März'), ('AP', 'April'), ('MA', 'Mai'), ('JN', 'Juni'), ('JU', 'Juli'), ('AU', 'August'), ('SE', 'September'), ('OK', 'Oktober'), ('NO', 'November'), ('DE', 'Dezember')], max_length=10)),
                ('betrag', models.IntegerField(default=0)),
                ('description', models.TextField(blank=True, max_length=2048, verbose_name='Bemerkungen')),
                ('mieter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='verwaltung.renter')),
                ('mietzinsprofil', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='verwaltung.rentprofile')),
                ('year', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='verwaltung.year')),
            ],
            options={
                'verbose_name': 'Mietzinseingänge',
                'verbose_name_plural': 'Mietzinseingänge',
            },
        ),
        migrations.CreateModel(
            name='RentalProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=0, max_length=200, verbose_name='Objektname')),
                ('description', models.TextField(max_length=2048, verbose_name='Beschreibung')),
                ('photo', models.ImageField(blank=True, default=0, upload_to='', verbose_name='Bild')),
                ('building', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='verwaltung.building')),
            ],
            options={
                'verbose_name': 'Mietobjekt',
                'verbose_name_plural': 'Mietobjekt',
            },
        ),
        migrations.AddField(
            model_name='rent',
            name='mietobject',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='verwaltung.rentalproperty'),
        ),
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.CharField(max_length=200, verbose_name='Projekt')),
                ('description', models.TextField(max_length=2048, verbose_name='Beschreibung')),
                ('betrag', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Investition (SFR)')),
                ('datum', models.DateField(default=datetime.datetime(2021, 7, 25, 9, 47, 21, 936580, tzinfo=utc))),
                ('mietobject', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='verwaltung.rentalproperty')),
            ],
            options={
                'verbose_name': 'Investment',
                'verbose_name_plural': 'Investment',
            },
        ),
    ]
