# Generated by Django 3.2.5 on 2021-07-11 15:16

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mieter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(blank=True, max_length=200, verbose_name='Firma')),
                ('first_name', models.CharField(max_length=200, verbose_name='Vorname')),
                ('last_name', models.CharField(max_length=200, verbose_name='Nachname')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('phone_number', models.CharField(max_length=200, verbose_name='Telefonnummer')),
                ('conto_number', models.CharField(default=0, max_length=200, verbose_name='IBAN Nummer')),
                ('address', models.CharField(default=0, max_length=200, verbose_name='Strasse')),
                ('address_Nr', models.IntegerField(default=0, verbose_name='Strassennummer')),
                ('city', models.CharField(default=0, max_length=200, verbose_name='Wohnort')),
                ('city_code', models.IntegerField(default=0, verbose_name='PLZ')),
                ('first_name_2nd', models.CharField(blank=True, max_length=200, verbose_name='Zweitmieter Vorname')),
                ('last_name_2nd', models.CharField(blank=True, max_length=200, verbose_name='Zweitmieter Nachname')),
                ('activ', models.BooleanField(default=False, verbose_name='aktiv')),
            ],
        ),
        migrations.CreateModel(
            name='Mietobjekt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=0, max_length=200, verbose_name='Objektname')),
                ('building', models.CharField(choices=[('H1', 'H1'), ('H3', 'H3'), ('H3A', 'H3A'), ('H5', 'H5'), ('H5A', 'H5A')], default=0, max_length=10)),
                ('description', models.TextField(max_length=2048, verbose_name='Beschreibung')),
                ('photo', models.ImageField(blank=True, default=0, upload_to='', verbose_name='Bild')),
            ],
        ),
        migrations.CreateModel(
            name='Mietzins',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200, verbose_name='Beschreibung')),
                ('rent', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Mietpreis (SFR)')),
                ('start_date', models.DateField(default=datetime.datetime(2021, 7, 11, 17, 16, 50, 349676))),
                ('end_date', models.DateField(default=datetime.datetime(2021, 7, 11, 17, 16, 50, 349676))),
                ('aktiv', models.BooleanField(default=False)),
                ('mietobject', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='verwaltung.mietobjekt')),
            ],
        ),
        migrations.CreateModel(
            name='Nebenkosten',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typ', models.CharField(choices=[('Heizung', 'Heizung'), ('Wasser', 'Wasser'), ('Allg. NK', 'Allg. NK')], max_length=10)),
                ('betrag', models.DecimalField(decimal_places=2, max_digits=6)),
                ('a_conto', models.CharField(choices=[('a', 'à conto'), ('p', 'pauschal')], default='a', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='Year',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typ', models.IntegerField(default=2010)),
            ],
        ),
        migrations.CreateModel(
            name='Unterhalt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.CharField(max_length=200, verbose_name='Projekt')),
                ('description', models.TextField(max_length=2048, verbose_name='Beschreibung')),
                ('betrag', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Investition (SFR)')),
                ('mietobject', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='verwaltung.mietobjekt')),
            ],
        ),
        migrations.CreateModel(
            name='Mietzinsprofil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(default=datetime.datetime(2021, 7, 11, 17, 16, 50, 351674))),
                ('end_date', models.DateField(default=datetime.datetime(2021, 7, 11, 17, 16, 50, 351674))),
                ('miete', models.ManyToManyField(to='verwaltung.Mietzins')),
                ('mieter', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='verwaltung.mieter')),
                ('nebenkosten', models.ManyToManyField(to='verwaltung.Nebenkosten')),
            ],
        ),
        migrations.CreateModel(
            name='Mietzinseingaenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum', models.DateField(default=datetime.datetime(2021, 7, 11, 17, 16, 50, 356671))),
                ('month', models.CharField(choices=[('JA', 'Januar'), ('FE', 'Februar'), ('MA', 'März'), ('AP', 'April'), ('MA', 'Mai'), ('JN', 'Juni'), ('JU', 'Juli'), ('AU', 'August'), ('SE', 'September'), ('OK', 'Oktober'), ('NO', 'November'), ('DE', 'Dezember')], max_length=10)),
                ('betrag', models.IntegerField(default=0)),
                ('mieter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='verwaltung.mieter')),
                ('mietzinsprofil', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='verwaltung.mietzinsprofil')),
                ('year', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='verwaltung.year')),
            ],
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(max_length=200)),
                ('votes', models.IntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='verwaltung.question')),
            ],
        ),
        migrations.CreateModel(
            name='MietobjektSummary',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('verwaltung.mietobjekt',),
        ),
        migrations.CreateModel(
            name='MietzinseingaengeSummary',
            fields=[
            ],
            options={
                'verbose_name': 'Mieteinnahmen',
                'verbose_name_plural': 'Mieteingänge',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('verwaltung.mietzinseingaenge',),
        ),
    ]
