# Generated by Django 3.2.5 on 2021-07-25 10:00

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('verwaltung', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='investment',
            old_name='betrag',
            new_name='amount',
        ),
        migrations.AlterField(
            model_name='investment',
            name='datum',
            field=models.DateField(default=datetime.datetime(2021, 7, 25, 10, 0, 41, 282304, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='rent',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2021, 7, 25, 10, 0, 41, 277307, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='rent',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2021, 7, 25, 10, 0, 41, 277307, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='rentprofile',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2021, 7, 25, 10, 0, 41, 278306, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='rentprofile',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2021, 7, 25, 10, 0, 41, 278306, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='rentreceipts',
            name='datum',
            field=models.DateField(default=datetime.datetime(2021, 7, 25, 10, 0, 41, 283304, tzinfo=utc)),
        ),
    ]
