# Generated by Django 3.2.5 on 2021-07-11 15:22

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('verwaltung', '0002_auto_20210711_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mietzins',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2021, 7, 11, 15, 22, 50, 62542, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='mietzins',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2021, 7, 11, 15, 22, 50, 62542, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='mietzinseingaenge',
            name='datum',
            field=models.DateField(default=datetime.datetime(2021, 7, 11, 15, 22, 50, 68538, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='mietzinsprofil',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2021, 7, 11, 15, 22, 50, 63537, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='mietzinsprofil',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2021, 7, 11, 15, 22, 50, 63537, tzinfo=utc)),
        ),
    ]
