# Generated by Django 3.2.5 on 2021-07-11 15:26

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('verwaltung', '0004_auto_20210711_1724'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MietzinseingaengeSummary',
        ),
        migrations.AlterField(
            model_name='mietzins',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2021, 7, 11, 15, 26, 52, 226931, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='mietzins',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2021, 7, 11, 15, 26, 52, 226931, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='mietzinseingaenge',
            name='datum',
            field=models.DateField(default=datetime.datetime(2021, 7, 11, 15, 26, 52, 233927, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='mietzinsprofil',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2021, 7, 11, 15, 26, 52, 228930, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='mietzinsprofil',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2021, 7, 11, 15, 26, 52, 227930, tzinfo=utc)),
        ),
    ]
