# Generated by Django 3.2.5 on 2021-07-13 14:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('verwaltung', '0005_auto_20210711_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mietzins',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2021, 7, 13, 14, 30, 4, 535454, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='mietzins',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2021, 7, 13, 14, 30, 4, 535454, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='mietzinseingaenge',
            name='datum',
            field=models.DateField(default=datetime.datetime(2021, 7, 13, 14, 30, 4, 551079, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='mietzinsprofil',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2021, 7, 13, 14, 30, 4, 535454, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='mietzinsprofil',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2021, 7, 13, 14, 30, 4, 535454, tzinfo=utc)),
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
