# Generated by Django 3.2.5 on 2021-07-13 18:07

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('verwaltung', '0006_auto_20210713_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mietzins',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2021, 7, 13, 18, 7, 1, 523245, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='mietzins',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2021, 7, 13, 18, 7, 1, 523245, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='mietzinseingaenge',
            name='datum',
            field=models.DateField(default=datetime.datetime(2021, 7, 13, 18, 7, 1, 523245, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='mietzinsprofil',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2021, 7, 13, 18, 7, 1, 523245, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='mietzinsprofil',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2021, 7, 13, 18, 7, 1, 523245, tzinfo=utc)),
        ),
    ]
