# Generated by Django 3.2.5 on 2021-07-17 14:05

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('verwaltung', '0009_auto_20210715_1859'),
    ]

    operations = [
        migrations.AddField(
            model_name='mietzinsprofil',
            name='activ',
            field=models.BooleanField(default=False, verbose_name='aktiv'),
        ),
        migrations.AlterField(
            model_name='building',
            name='name',
            field=models.CharField(default=1, max_length=200, verbose_name='Objektname'),
        ),
        migrations.AlterField(
            model_name='mietzins',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2021, 7, 17, 14, 5, 50, 627091, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='mietzins',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2021, 7, 17, 14, 5, 50, 627091, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='mietzinseingaenge',
            name='datum',
            field=models.DateField(default=datetime.datetime(2021, 7, 17, 14, 5, 50, 633088, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='mietzinsprofil',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2021, 7, 17, 14, 5, 50, 628091, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='mietzinsprofil',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2021, 7, 17, 14, 5, 50, 628091, tzinfo=utc)),
        ),
    ]
