# Generated by Django 3.2.5 on 2021-07-21 15:35

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('verwaltung', '0010_auto_20210717_1605'),
    ]

    operations = [
        migrations.AddField(
            model_name='unterhalt',
            name='datum',
            field=models.DateField(default=datetime.datetime(2021, 7, 21, 15, 35, 4, 196129, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='mietzins',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2021, 7, 21, 15, 35, 4, 189133, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='mietzins',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2021, 7, 21, 15, 35, 4, 189133, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='mietzinseingaenge',
            name='datum',
            field=models.DateField(default=datetime.datetime(2021, 7, 21, 15, 35, 4, 196129, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='mietzinsprofil',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2021, 7, 21, 15, 35, 4, 191132, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='mietzinsprofil',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2021, 7, 21, 15, 35, 4, 191132, tzinfo=utc)),
        ),
    ]
